InventoryFrontEnd/InventoryFrontEnd/Controllers/InventoryController.cs
using InventoryFrontEnd.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace InventoryFrontEnd.Controllers
{
    public class InventoryController : Controller
    {

        //SHOW ALL Campus
        public ActionResult Campus()
        {
            Modelall mymodel = new Modelall();
            mymodel.Allcampus = campuses();
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Inventory/Campus.cshtml", mymodel);
            }
           

        }

        public IEnumerable<Campuses> campuses()
        {

            IEnumerable<Campuses> ec = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/");

            var consumedata = hc.GetAsync("Campuses");
            consumedata.Wait();


            var dataread = consumedata.Result;
            if (dataread.IsSuccessStatusCode)
            {
                var results = dataread.Content.ReadAsAsync<IList<Campuses>>();
                results.Wait();
                ec = results.Result;
            }
            else if (dataread.StatusCode == HttpStatusCode.NotFound)
            {
                ec = Enumerable.Empty<Campuses>();
                ViewBag.Message = "No Locality Found.";
            }
            else
            {
                ec = Enumerable.Empty<Campuses>();
                ViewBag.Message = "Unable to display locality, please email to it@golden-success.com for help.";
            }
            return ec;
        }

        // ADD CAMPUS
        [HttpPost]
        [Route("insert/feedback/view2")]
        public ActionResult AddCampuscontroll(string add_campusnamevalue)
        {


            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Campus_name=" + add_campusnamevalue;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Add/Campus?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();

                        // Redirect back to the referring page
                        return Redirect(Request.UrlReferrer.ToString());
                    }
                }
                catch (WebException ex)
                {
                    HttpWebResponse res = (HttpWebResponse)ex.Response;
                    Stream receiveStream = res.GetResponseStream();
                    using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                    {
                        return Content("Catch: " + readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                    }
                }
            }
            catch (WebException ex)
            {
                HttpWebResponse res = (HttpWebResponse)ex.Response;
                Stream receiveStream = res.GetResponseStream();
                using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                {
                    return Content(readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                }
            }

        }

        //UPDATE CAMPUS
        [HttpPost]
        public ActionResult updatecampus(string update_Campus_id, string update_campus_name)
        {


            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Campus_id=" + update_Campus_id + "&Campus_name=" + update_campus_name;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Modify/Campus?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();

                        // Redirect back to the referring page
                        return Redirect(Request.UrlReferrer.ToString());
                    }
                }
                catch (WebException ex)
                {
                    HttpWebResponse res = (HttpWebResponse)ex.Response;
                    Stream receiveStream = res.GetResponseStream();
                    using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                    {
                        return Content("Catch: " + readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                    }
                }
            }
            catch (WebException ex)
            {
                HttpWebResponse res = (HttpWebResponse)ex.Response;
                Stream receiveStream = res.GetResponseStream();
                using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                {
                    return Content(readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                }
            }

        }

        //SHOW ALL ITEMS
        public ActionResult Item_list(string Campus_name)
        {
            Modelall mymodel = new Modelall();
            mymodel.Item_list = Allitems(Campus_name);
            mymodel.Allbrand = Brands(Campus_name);
            mymodel.Room_list = Allrooms(Campus_name);

            mymodel.Allroomcounters = counterallrooms(Campus_name);
            mymodel.AllITassetcounters = counterallITAsset(Campus_name);
            mymodel.Alllogscounters = counterlogs(Campus_name);
            ViewBag.Campus_name = Campus_name;
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Inventory/item_list.cshtml", mymodel);
            }

        }
        public IEnumerable<Items> Allitems(string Campus_name)
        {

            IEnumerable<Items> ec = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Item/");

            var consumedata = hc.GetAsync("All?Campus_name=" + Campus_name);
            consumedata.Wait();


            var dataread = consumedata.Result;
            if (dataread.IsSuccessStatusCode)
            {
                var results = dataread.Content.ReadAsAsync<IList<Items>>();
                results.Wait();
                ec = results.Result;
            }
            else if (dataread.StatusCode == HttpStatusCode.NotFound)
            {
                ec = Enumerable.Empty<Items>();
                ViewBag.Message = "No Locality Found.";
            }
            else
            {
                ec = Enumerable.Empty<Items>();
                ViewBag.Message = "Unable to display locality, please email to it@golden-success.com for help.";
            }
            return ec;
        }

        //ADD ITEMS 

        [HttpPost]
        public ActionResult createitems(string add_item_name, string add_model, string add_brand, string add_serial_number, string add_item_type, string add_item_status, string add_item_department, string add_date, string add_room, string add_campus)
        {
            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Item_name=" + add_item_name + "&Model=" + add_model + "&Brand=" + add_brand + "&Serial_number=" + add_serial_number + "&Item_type=" + add_item_type + "&Item_status=" + add_item_status + "&Department=" + add_item_department + "&Date_now=" + add_date + "&Room_name=" + add_room + "&Campus_name=" + add_campus;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Add/Newitems?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();

                        // Redirect back to the referring page

InventoryFrontEnd/InventoryFrontEnd/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryInterface.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View();
            }
        }
    }
}

InventoryFrontEnd/InventoryFrontEnd/Views/Shared/_Layout.cshtml
@using InventoryFrontEnd.Models;
@model Modelall

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="vh-100 vw-100">
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg navbar-light bg-primary fixed-top" style="padding: 5px; font-size: 18px;">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="#">
                            <img src="~/Content/gsc-logo-header.png" alt="Your Logo" height="50" class="d-inline-block align-top">
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link hover-scale-2" href="@Url.Action("Campus", "Inventory", new { campus_name = ViewBag.campus_name })">Campus</a>
                                </li>

                                

                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Index", "Profile")">Profile</a>
                                </li>
                            </ul>
                            <form class="d-flex" role="search">
                                <a class="nav-link" href="@Url.Action("logout", "dashboard")">Log-out</a>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
        </nav>
    </div>


   


    <script>
        // Function to check session status at regular intervals
        function checkSessionStatus() {
            $.ajax({
                url: '/Account/CheckSession', // Endpoint to check session status
                success: function (response) {
                    // Session is still active
                },
                error: function (xhr, status, error) {
                    if (xhr.status == 401) { // Unauthorized (session expired)
                        // Perform logout action
                        window.location.href = '/dashboard/logout'; // Redirect to logout endpoint
                    }
                }
            });
        }

        // Check session status every 5 minutes (adjust as needed)
        setInterval(checkSessionStatus, 300000); // 5 minutes in milliseconds
    </script>



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>