InventoryFrontEnd/InventoryFrontEnd/Controllers/ApparelController.cs
using InventoryFrontEnd.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace InventoryFrontEnd.Controllers
{
    public class ApparelController : Controller
    {
        // SHOW ALL AVAILABLE APPAREL

        public ActionResult Apparel_stock(string Campus_name)
        {
            Modelall mymodel = new Modelall();
            mymodel.Allapparel_stock = Apparelstock(Campus_name);
            mymodel.Allgrades = grades(Campus_name);
            mymodel.Allsize = sizes(Campus_name);
            mymodel.Allapparel_type = clothes_type(Campus_name);
            mymodel.AllApparelavailablecounters = counterapparelavil(Campus_name);
            ViewBag.campus_name = Campus_name;
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Apparel/Apparel_stock.cshtml", mymodel);
            }

        }

        public IEnumerable<Apparel_stock> Apparelstock(string Campus_name)
        {

            IEnumerable<Apparel_stock> ec = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri(ConfigurationManager.AppSettings["API_Path"] + "API/Apparel/Available/");

            var consumedata = hc.GetAsync("stock?campus_name=" + Campus_name);
            consumedata.Wait();


            var dataread = consumedata.Result;
            if (dataread.IsSuccessStatusCode)
            {
                var results = dataread.Content.ReadAsAsync<IList<Apparel_stock>>();
                results.Wait();
                ec = results.Result;
            }
            else if (dataread.StatusCode == HttpStatusCode.NotFound)
            {
                ec = Enumerable.Empty<Apparel_stock>();
                ViewBag.Message = "No Locality Found.";
            }
            else
            {
                ec = Enumerable.Empty<Apparel_stock>();
                ViewBag.Message = "Unable to display locality, please email to it@golden-success.com for help.";
            }
            return ec;
        }


        // ADD UNIFORM

        [HttpPost]
        [Route("insert/feedback/view2")]
        public ActionResult adduniform(string add_grade, string add_uniform_type, string add_sizes, string add_stocks, string add_campus_name)
        {


            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Grade_level=" + add_grade + "&Apparel_type=" + add_uniform_type + "&Size=" + add_sizes + "&Quantity=" + add_stocks + "&Campus_name=" + add_campus_name;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Apparel/ADD/Apparelavailable?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();


                        string referringUrl = Request.UrlReferrer != null ? Request.UrlReferrer.AbsoluteUri : "";


                        return Redirect(referringUrl);
                    }
                }
                catch (WebException ex)
                {
                    HttpWebResponse res = (HttpWebResponse)ex.Response;
                    Stream receiveStream = res.GetResponseStream();
                    using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                    {
                        return Content("Catch: " + readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                    }
                }
            }
            catch (WebException ex)
            {
                HttpWebResponse res = (HttpWebResponse)ex.Response;
                Stream receiveStream = res.GetResponseStream();
                using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                {
                    return Content(readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                }
            }
        }

        // ADD Quantity

        [HttpPost]
        public ActionResult addstock(string add_uniform_id, string add_stock, string add_transaction, string add_grade_level, string add_clothes_type, string add_size, string add_campus_name)
        {


            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Apparel_ID=" + add_uniform_id + "&stockChange=" + add_stock + "&Transaction=" + add_transaction + "&Grade_level=" + add_grade_level + "&Apparel_type=" + add_clothes_type + "&Size=" + add_size + "&Campus_name=" + add_campus_name;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Apparel/ADD/STOCK?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();

                        // Get the referring URL (current page)
                        string referringUrl = Request.UrlReferrer != null ? Request.UrlReferrer.AbsoluteUri : "";

                        // Redirect back to the referring URL (current page)
                        return Redirect(referringUrl);
                    }
                }
                catch (WebException ex)
                {
                    HttpWebResponse res = (HttpWebResponse)ex.Response;
                    Stream receiveStream = res.GetResponseStream();
                    using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                    {
                        return Content("Catch: " + readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                    }
                }
            }
            catch (WebException ex)
            {
                HttpWebResponse res = (HttpWebResponse)ex.Response;
                Stream receiveStream = res.GetResponseStream();
                using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                {
                    return Content(readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                }
            }
        }

        // SHOW ALL GRADES

        public ActionResult grade_list(string Campus_name)
        {
            Modelall mymodel = new Modelall();
            mymodel.Allgrades = grades(Campus_name);
            mymodel.AllGradecounters = countergrade(Campus_name);
            ViewBag.firstName = Session["FirstName"];
            ViewBag.LastName = Session["LastName"];
            ViewBag.campusName = Session["campusName"];
            ViewBag.campus_name = Campus_name;
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Apparel/grade_list.cshtml", mymodel);
            }
        }

        public IEnumerable<Grades> grades(string Campus_name)
        {

            IEnumerable<Grades> ec = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri(ConfigurationManager.AppSettings["API_Path"] + "API/Apparel/Grade/");

            var consumedata = hc.GetAsync("list?Campus_name=" + Campus_name);
            consumedata.Wait();


            var dataread = consumedata.Result;
            if (dataread.IsSuccessStatusCode)
            {
                var results = dataread.Content.ReadAsAsync<IList<Grades>>();
                results.Wait();
                ec = results.Result;
            }
            else if (dataread.StatusCode == HttpStatusCode.NotFound)
            {
                ec = Enumerable.Empty<Grades>();
                ViewBag.Message = "No Locality Found.";
            }
            else
            {
                ec = Enumerable.Empty<Grades>();
                ViewBag.Message = "Unable to display locality, please email to it@golden-success.com for help.";
            }
            return ec;
        }



        //ADD Grade level
        [HttpPost]
        public ActionResult addgradelvl(string add_gradelvl, string add_campus_name)
        {
            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Grade_level=" + add_gradelvl + "&Campus_name=" + add_campus_name;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Apparel/ADD/Grade?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";

InventoryFrontEnd/InventoryFrontEnd/Views/Dashboard/Index.cshtml
@using InventoryFrontEnd.Models;
@model Modelall
@{

    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/With_Side_Bar.cshtml";

}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .hover-scale:hover {
            transform: scale(1.05);
            transition: transform 0.2s ease-in-out;
        }
    </style>
</head>
<body class="mt-3">

    <div class="col-md-9 h-100">
        <div class="sticky-xl-top">
            <div class="card overflow-y-auto">
                <div class="card-body mt-3">
                    <h2 id="room-label" class="text-center">@ViewBag.campus_name </h2>
                    <h1 class="text-center">DASHBOARD</h1>
                    @if (Session["UserRole"] == null || Session["UserRole"].ToString() != "Apparel Incharge")
                    {
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">Item List</h5>
                                        @foreach (var item in Model.AllITassetcounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("Item_list", "Inventory", new { campus_name = ViewBag.campus_name })" class="btn btn-success d-block mx-auto hover">View</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">All rooms</h5>
                                        @foreach (var item in Model.Allroomcounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("rooms", "Inventory", new { campus_name = ViewBag.campus_name })" class="btn btn-success d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">All Employee</h5>
                                        @foreach (var item in Model.Allemployeecounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("employeelist", "Inventory", new { campus_name = ViewBag.campus_name })" class="btn btn-success d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">Asset Logs</h5>
                                        @foreach (var item in Model.Alllogscounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("itemlogs", "Inventory", new { campus_name = ViewBag.campus_name })" class="btn btn-success d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">Brand List</h5>
                                        @foreach (var item in Model.Allbrandcounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("brandlist", "Inventory", new { campus_name = ViewBag.campus_name })" class="btn btn-success d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }

                    @if (Session["UserRole"] == null || Session["UserRole"].ToString() != "IT Asset Incharge")
                    {
                        <h1 class="text-center">Apparel List</h1>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">APPAREL AVAILABLE</h5>
                                        @foreach (var item in Model.AllApparelavailablecounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("Apparel_stock", "Apparel", new { campus_name = ViewBag.campus_name })" class="btn btn-primary d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">Grade List</h5>
                                        @foreach (var item in Model.AllGradecounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("grade_list", "Apparel", new { campus_name = ViewBag.campus_name })" class="btn btn-primary d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">Size List</h5>
                                        @foreach (var item in Model.AllSizecounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("size_list", "Apparel", new { campus_name = ViewBag.campus_name })" class="btn btn-primary d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">Claim Apparel List</h5>
                                        @foreach (var item in Model.Allclaimcounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("Claim_stub", "Apparel", new { campus_name = ViewBag.campus_name })" class="btn btn-primary d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">All Apparel Type</h5>
                                        @foreach (var item in Model.Allappareltypecounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("Appareltype_list", "Apparel", new { campus_name = ViewBag.campus_name })" class="btn btn-primary d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title text-center">Apparel Record list</h5>
                                        @foreach (var item in Model.Allapparelrecordcounters)
                                        {
                                            <h1 class="text-center">@Html.DisplayFor(modelItem => item.Counter)</h1>
                                        }
                                        <a href="@Url.Action("employeelist", "Inventory", new { campus_name = ViewBag.campus_name })" class="btn btn-primary d-block mx-auto">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>

   
   




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>